version: 1
disable_existing_loggers: False

formatters:
    brief:
        format: "%(message)s"
    extend:
        format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"

handlers:
    console_handler:
        class: logging.StreamHandler
        level: WARNING
        formatter: brief
        stream: ext://sys.stdout

    log_file_handler: &file_rotating_handler
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: extend
        filename: twlived.log
        encoding: utf8
        maxBytes: 512000
        backupCount: 5

    requests_handler:
        <<: *file_rotating_handler
        filename: requests.log

loggers:
    urllib3:
        level: DEBUG
        handlers:
            - requests_handler
        propagate: no

    twitch_api:
        level: DEBUG
        handlers:
            - log_file_handler
        propagate: no

    log:
        level: DEBUG
        handlers:
            - console_handler
            - log_file_handler
        propagate: no

